services:
  - type: web
    name: coda-ai-assistant
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: CODA_API_KEY
        value: "47b5abed-b00e-4029-a88b-da2e576eae36"
      - key: GEMINI_API_KEY
        value: "AIzaSyDxkiMGS2AkjVsaL4DrI5Q7BeEoyh93kt0"
